import { Alert, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { useState } from 'react';
import { Card, Label, Money, PrimaryButton, SectionTitle } from '@/components/ui';
import { FAMILY_AMOUNTS, FAMILY_INTERACTIONS, GIFTS } from '@/config/balance';
import { askBrother, giveFinancialHelp, performInteraction, purchaseGift, repayBrother } from '@/game/relationships/family';
import { daysBetween, formatGameDate, relationLabel } from '@/game/time/time';
import { GiftTier, InteractionType } from '@/models/game';
import { useGameStore } from '@/store/gameStore';
import { colors, spacing } from '@/theme';

const relationName = { MOTHER: 'Mother', FATHER: 'Father', BROTHER: 'Brother', GRANDMOTHER: 'Grandmother', GRANDFATHER: 'Grandfather' } as const;
const activityTypes: InteractionType[]=['EAT_TOGETHER','SMALL_OUTING','FAMILY_DINNER','PARTY'];
const giftTiers: GiftTier[]=['SMALL','MEDIUM','LARGE','LUXURY'];
export default function PersonProfile(){
  const {id}=useLocalSearchParams<{id:string}>(); const game=useGameStore(state=>state.game)!; const update=useGameStore(state=>state.update); const [amount,setAmount]=useState('100'); const member=game.relationships.find(item=>item.id===id);
  if(!member)return <View style={s.missing}><Text style={s.name}>Person not found</Text><PrimaryButton title="BACK" onPress={()=>router.back()}/></View>;
  const lastDays=member.lastInteractionGameDate?daysBetween(member.lastInteractionGameDate,game.date):null; const debt=game.personalDebts.find(item=>item.creditorId===member.id&&item.status==='ACTIVE');
  const interact=(type:InteractionType)=>{const cfg=FAMILY_INTERACTIONS[type];Alert.alert(cfg.label,`COST\n€${cfg.cost}\n\nTIME\n${cfg.timeHours} HOURS\n\nEFFECT\nRelationship may improve.`,[{text:'Cancel',style:'cancel'},{text:'Continue',onPress:()=>{try{update(state=>performInteraction(state,member.id,type));Alert.alert('Time well spent',`${cfg.timeHours} in-game hours passed.`)}catch(error){Alert.alert('Not available',(error as Error).message)}}}])};
  const chooseActivity=()=>Alert.alert('Go out together','Choose an activity.',[...activityTypes.map(type=>({text:`${FAMILY_INTERACTIONS[type].label} · €${FAMILY_INTERACTIONS[type].cost}`,onPress:()=>interact(type)})),{text:'Cancel'}]);
  const chooseGift=()=>Alert.alert('Give gift','Price is not the same as meaning. Repeated gifts have diminishing impact.',[...giftTiers.map(tier=>({text:`${GIFTS[tier].label} · €${GIFTS[tier].cost.toLocaleString()}`,onPress:()=>Alert.alert(`${GIFTS[tier].label} gift`,`COST\n€${GIFTS[tier].cost.toLocaleString()}\n\nTIME\n1 HOUR\n\nEFFECT\nDepends on personality and gift history.`,[{text:'Cancel',style:'cancel'},{text:'Buy & Give',onPress:()=>{try{update(state=>purchaseGift(state,member.id,tier))}catch(error){Alert.alert('Gift failed',(error as Error).message)}}}])})),{text:'Cancel'}]);
  const help=(kind:'GIFT'|'LOAN')=>{const value=Number(amount);try{update(state=>giveFinancialHelp(state,member.id,value,kind));Alert.alert('Help recorded',`${member.name} will remember your ${kind==='LOAN'?'personal loan':'support'}.`)}catch(error){Alert.alert('Unable to help',(error as Error).message)}};
  const ask=(value:number)=>{let resultMessage='';update(state=>{const result=askBrother(state,value);resultMessage=result.message;return result.state});Alert.alert(member.name,resultMessage)};
  return <ScrollView style={s.root} contentContainerStyle={s.content}><Text onPress={()=>router.back()} style={s.back}>‹ Family</Text><View style={s.hero}><View style={s.avatar}><Text style={s.initial}>{member.name[0]}</Text></View><Text style={s.name}>{member.name}</Text><Text style={s.relation}>{relationName[member.relationType]}</Text><Text style={s.contact}>{member.contactStatus.replace('_',' ')}</Text></View>
    <Card style={s.stats}><View><Label>Relationship</Label><Text style={s.value}>{relationLabel(member.relationshipScore)}</Text><Text style={s.score}>{member.relationshipScore}/100</Text></View><View><Label>Trust</Label><Text style={s.value}>{member.trust}/100</Text></View><View><Label>Mood</Label><Text style={s.value}>{member.mood}</Text></View></Card><Text style={s.last}>{lastDays===null?'No interaction yet':lastDays===0?'Last contact today':`Last contact ${lastDays} days ago`} · Birthday {String(member.birthday.day).padStart(2,'0')}.{String(member.birthday.month).padStart(2,'0')}.</Text>
    <SectionTitle>Connect</SectionTitle><View style={s.grid}><View style={s.half}><PrimaryButton title="CALL" onPress={()=>interact('CALL')}/></View><View style={s.half}><PrimaryButton title="VISIT" tone="dark" onPress={()=>interact('VISIT')}/></View><View style={s.half}><PrimaryButton title="GIVE GIFT" tone="dark" onPress={chooseGift}/></View><View style={s.half}><PrimaryButton title="GO OUT" tone="dark" onPress={chooseActivity}/></View></View>
    <SectionTitle>Financial help</SectionTitle><Card style={s.help}><Text style={s.copy}>Give support or record a simple personal loan.</Text><View style={s.amounts}>{[100,500,2000].map(value=><Text key={value} onPress={()=>setAmount(String(value))} style={s.chip}>€{value.toLocaleString()}</Text>)}</View><TextInput value={amount} onChangeText={setAmount} keyboardType="numeric" placeholder="Custom amount" placeholderTextColor={colors.muted} style={s.input}/><View style={s.grid}><View style={s.half}><PrimaryButton title="GIVE MONEY" disabled={Number(amount)>game.cash} onPress={()=>help('GIFT')}/></View><View style={s.half}><PrimaryButton title="PERSONAL LOAN" tone="dark" disabled={Number(amount)>game.cash} onPress={()=>help('LOAN')}/></View></View></Card>
    {member.relationType==='BROTHER'&&<><SectionTitle>Brother financing</SectionTitle>{debt&&<Card style={s.help}><Label>You owe {member.name}</Label><Money value={debt.amount-debt.repaidAmount}/><PrimaryButton title="REPAY €100" disabled={game.cash<=0} onPress={()=>update(state=>repayBrother(state,debt.id,Math.min(100,state.cash)))}/></Card>}<Text style={s.copy}>Ask once per in-game month. Approval depends on trust and the amount.</Text><View style={s.actions}>{FAMILY_AMOUNTS.map(value=><PrimaryButton key={value} title={`ASK FOR €${value.toLocaleString()}`} tone="dark" onPress={()=>ask(value)}/>)}</View></>}
    <SectionTitle>Memories & history</SectionTitle>{member.memories.length===0?<Card><Text style={s.copy}>Shared moments will appear here.</Text></Card>:member.memories.slice(0,12).map(item=><View key={item.id} style={s.history}><View style={s.dot}/><View style={s.historyText}><Text style={s.historyTitle}>{item.text}</Text><Text style={s.historyDate}>{formatGameDate(item.gameDate)} · Importance {item.importance}/3</Text></View></View>)}
  </ScrollView>;
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:colors.bg},content:{padding:spacing.md,paddingTop:55,paddingBottom:90},missing:{flex:1,backgroundColor:colors.bg,padding:30,justifyContent:'center',gap:20},back:{color:colors.gold,fontWeight:'800',fontSize:17},hero:{alignItems:'center',paddingVertical:25},avatar:{width:82,height:82,borderRadius:28,backgroundColor:'#29251D',borderWidth:1,borderColor:'#67532D',alignItems:'center',justifyContent:'center'},initial:{fontSize:36,fontWeight:'900',color:colors.gold},name:{color:colors.text,fontSize:30,fontWeight:'900',marginTop:12},relation:{color:colors.muted,fontSize:15,marginTop:3},contact:{color:colors.green,fontWeight:'900',fontSize:10,textTransform:'uppercase',marginTop:8,letterSpacing:1},stats:{flexDirection:'row',justifyContent:'space-between'},value:{color:colors.text,fontWeight:'900',fontSize:16,marginTop:6},score:{color:colors.muted,fontSize:10,marginTop:2},last:{color:colors.muted,textAlign:'center',fontSize:12,marginTop:11},grid:{flexDirection:'row',flexWrap:'wrap',gap:9},half:{width:'48%'},help:{gap:12},copy:{color:colors.muted,lineHeight:19},amounts:{flexDirection:'row',gap:8},chip:{color:colors.gold,backgroundColor:colors.surface2,borderColor:colors.border,borderWidth:1,borderRadius:12,paddingVertical:9,paddingHorizontal:13,fontWeight:'800'},input:{height:50,borderRadius:14,backgroundColor:colors.surface2,color:colors.text,borderWidth:1,borderColor:colors.border,paddingHorizontal:15,fontSize:17},actions:{gap:8},history:{flexDirection:'row',paddingVertical:12,borderBottomColor:colors.border,borderBottomWidth:1},dot:{width:8,height:8,borderRadius:4,backgroundColor:colors.gold,marginTop:5,marginRight:12},historyText:{flex:1},historyTitle:{color:colors.text,fontWeight:'700'},historyDate:{color:colors.muted,fontSize:11,marginTop:4}});
