import { Alert, ScrollView, StyleSheet, Text, View } from "react-native";
import { router, type Href } from "expo-router";
import { Card, Label, Money, PrimaryButton, SectionTitle } from "@/components/ui";
import { DEALERSHIP_TIERS, EXPANSIONS } from "@/game/businesses/carDealership/config";
import { dealershipReport, expandDealership, openDealership } from "@/game/businesses/carDealership/carDealership";
import type { DealershipTier } from "@/game/businesses/carDealership/types";
import { useGameStore } from "@/store/gameStore";
import { colors } from "@/theme";

export default function DealershipDashboard() {
  const game = useGameStore((state) => state.game), update = useGameStore((state) => state.update);
  if (!game) return null;
  const dealership = game.carDealership.dealerships[0];
  const confirm = (title: string, detail: string, fn: () => void) => Alert.alert(title, detail, [{ text: "Cancel", style: "cancel" }, { text: "Confirm", onPress: () => { try { fn(); } catch (error) { Alert.alert("Action unavailable", (error as Error).message); } } }]);
  if (!dealership) return <ScrollView style={s.root} contentContainerStyle={s.content}>
    <PrimaryButton title="‹ BUSINESS" tone="dark" onPress={() => router.replace("/(tabs)/business")} /><Text style={s.kicker}>NEW BUSINESS</Text><Text style={s.title}>Open Empire Motors.</Text><Text style={s.copy}>Choose a starting scale. Startup consumes one game day and creates a fully managed business entity compatible with the employee system.</Text>
    {(Object.keys(DEALERSHIP_TIERS) as DealershipTier[]).map((tier) => { const config = DEALERSHIP_TIERS[tier]; return <Card key={tier} style={s.card}><Label>{tier}</Label><Text style={s.name}>{config.label}</Text><Money value={config.startupCost} /><Text style={s.copy}>Capacity {config.capacity} vehicles · Starting reputation {config.reputation}/100</Text><PrimaryButton title={`OPEN ${tier} DEALERSHIP`} disabled={game.cash < config.startupCost} onPress={() => confirm(config.label, `Startup cost €${config.startupCost.toLocaleString()}\nTime: 1 game day`, () => update((state) => openDealership(state, tier)))} /></Card>; })}
  </ScrollView>;
  const business = game.businesses.find((item) => item.id === dealership.businessId)!, report = dealershipReport(game, dealership.id), active = dealership.vehicles.filter((item) => item.status !== "SOLD").length;
  return <ScrollView style={s.root} contentContainerStyle={s.content}>
    <PrimaryButton title="‹ BUSINESS" tone="dark" onPress={() => router.replace("/(tabs)/business")} /><Text style={s.kicker}>CAR DEALERSHIP · {game.carDealership.marketState} MARKET</Text><Text style={s.title}>{dealership.name}</Text>
    <Card style={s.hero}><View><Label>Reputation</Label><Text style={s.score}>{dealership.reputation.toFixed(0)}/100</Text></View><View><Label>Inventory</Label><Text style={s.score}>{active}/{dealership.capacity}</Text></View><View><Label>Inventory value</Label><Money value={report.inventoryValue} /></View><View><Label>Automation</Label><Text style={s.score}>{business.management.automationEfficiency}%</Text></View></Card>
    <View style={s.quick}><View style={s.half}><PrimaryButton title="BUY CARS" onPress={() => router.push("/dealership/market" as Href)} /></View><View style={s.half}><PrimaryButton title="INVENTORY / WORKSHOP" tone="dark" onPress={() => router.push("/dealership/inventory" as Href)} /></View><View style={s.half}><PrimaryButton title="STAFF" tone="dark" onPress={() => router.push(`/staff?businessId=${dealership.businessId}` as Href)} /></View><View style={s.half}><PrimaryButton title="AUTOMATION" tone="dark" onPress={() => router.push(`/management?businessId=${dealership.businessId}` as Href)} /></View></View>
    <SectionTitle>Financials</SectionTitle><Card style={s.card}>{[["Revenue", report.revenue], ["Vehicle purchases", -report.vehiclePurchaseCost], ["Repairs", -report.repairCost], ["Preparation", -report.preparationCost], ["Salaries", -report.salaries], ["Holding costs", -report.holdingCost], ["Net profit", report.netProfit]].map(([label, amount]) => <View key={label as string} style={s.line}><Label>{label}</Label><Money value={amount as number} /></View>)}<Text style={s.copy}>Average margin {report.averageMargin.toFixed(1)}% · Average days to sell {report.averageDaysToSell.toFixed(1)}</Text></Card>
    <SectionTitle>Expand dealership</SectionTitle>{(Object.keys(EXPANSIONS) as Array<keyof typeof EXPANSIONS>).map((type) => { const config = EXPANSIONS[type]; return <Card key={type} style={s.card}><Text style={s.name}>{type.replaceAll("_", " ")}</Text><Text style={s.copy}>€{config.cost.toLocaleString()} · {config.days} game days{config.capacity ? ` · +${config.capacity} capacity` : ""}</Text><PrimaryButton title="START EXPANSION" tone="dark" disabled={game.cash < config.cost} onPress={() => confirm(type, `Cost €${config.cost.toLocaleString()}\nCompletion: ${config.days} game days`, () => update((state) => expandDealership(state, dealership.id, type)))} /></Card>; })}
    <SectionTitle>Recent sales</SectionTitle>{dealership.sales.slice(0, 5).map((sale) => <Card key={sale.id} style={s.line}><View><Text style={s.name}>{sale.vehicleName}</Text><Text style={s.copy}>{sale.daysToSell} days in stock</Text></View><Money value={sale.profit} /></Card>)}{!dealership.sales.length && <Text style={s.copy}>No vehicle sales yet.</Text>}
  </ScrollView>;
}
const s = StyleSheet.create({ root: { flex: 1, backgroundColor: colors.bg }, content: { padding: 18, paddingTop: 55, paddingBottom: 110, gap: 12 }, kicker: { color: colors.gold, fontWeight: "900", letterSpacing: 1 }, title: { color: colors.text, fontSize: 32, fontWeight: "900" }, copy: { color: colors.muted, lineHeight: 21 }, card: { gap: 11 }, name: { color: colors.text, fontSize: 18, fontWeight: "900" }, hero: { flexDirection: "row", flexWrap: "wrap", gap: 20 }, score: { color: colors.text, fontSize: 22, fontWeight: "900", marginTop: 4 }, quick: { flexDirection: "row", flexWrap: "wrap", gap: 10 }, half: { width: "48%" }, line: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 10 } });
