import { useState } from "react";
import { Alert, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { router, useLocalSearchParams, type Href } from "expo-router";
import { Card, Label, Money, PrimaryButton, SectionTitle } from "@/components/ui";
import { PREPARATIONS, REPAIRS } from "@/game/businesses/carDealership/config";
import { buyVehicle, inspectVehicle, listVehicle, negotiateVehicle, prepareVehicle, removeVehicleListing, repairVehicle, sellVehicle } from "@/game/businesses/carDealership/carDealership";
import type { PreparationLevel, PriceStrategy, RepairLevel } from "@/game/businesses/carDealership/types";
import { recommendedPriceRange, vehicleRisk } from "@/game/businesses/carDealership/valuation";
import type { GameState } from "@/models/game";
import { useGameStore } from "@/store/gameStore";
import { colors } from "@/theme";

export default function VehicleDetail() {
  const { id } = useLocalSearchParams<{ id: string }>(), game = useGameStore((state) => state.game), update = useGameStore((state) => state.update);
  const [offer, setOffer] = useState(""), [custom, setCustom] = useState("");
  if (!game) return null;
  const dealership = game.carDealership.dealerships[0], marketVehicle = game.carDealership.marketOffers.find((item) => item.id === id), owned = dealership?.vehicles.find((item) => item.id === id), vehicle = marketVehicle ?? owned;
  if (!vehicle) return <View style={s.root}><Text style={s.title}>Vehicle unavailable</Text><PrimaryButton title="BACK" onPress={() => router.replace("/dealership" as Href)} /></View>;
  const run = (title: string, detail: string, fn: (state: GameState) => GameState, back = false) => Alert.alert(title, detail, [{ text: "Cancel", style: "cancel" }, { text: "Confirm", onPress: () => { try { update(fn); if (back) router.replace(marketVehicle ? "/dealership/market" as Href : "/dealership/inventory" as Href); } catch (error) { Alert.alert("Action failed", (error as Error).message); } } }]);
  const range = recommendedPriceRange(vehicle), estimatedProfit = (vehicle.askingPrice ?? vehicle.estimatedMarketValue) - (vehicle.purchasePrice || vehicle.sellerPrice) - vehicle.repairCost - vehicle.preparationCost - vehicle.holdingCost;
  return <ScrollView style={s.root} contentContainerStyle={s.content}><PrimaryButton title="‹ BACK" tone="dark" onPress={() => router.replace(marketVehicle ? "/dealership/market" as Href : "/dealership/inventory" as Href)} />
    <Text style={s.kicker}>{vehicle.category.replaceAll("_", " ")} · {vehicle.status}</Text><Text style={s.title}>{vehicle.brand} {vehicle.model}</Text><Text style={s.variant}>{vehicle.modelVariant} · {vehicle.year} · {vehicle.color}</Text>
    <Card style={s.hero}><View><Label>{marketVehicle ? "Seller price" : "Purchase price"}</Label><Money value={marketVehicle ? vehicle.sellerPrice : vehicle.purchasePrice} /></View><View><Label>Market value</Label><Money value={vehicle.estimatedMarketValue} /></View><View><Label>Estimated profit</Label><Money value={estimatedProfit} /></View></Card>
    <Card style={s.card}><Text style={s.copy}>{vehicle.mileage.toLocaleString()} km · {vehicle.fuelType} · {vehicle.transmission}</Text><Text style={s.copy}>Condition {vehicle.condition}% · Mechanical {vehicle.mechanicalCondition}% · Cosmetic {vehicle.cosmeticCondition}%</Text><Text style={s.copy}>Demand {vehicle.demand} · Rarity {vehicle.rarity} · Risk {vehicleRisk(vehicle)}</Text><Text style={s.copy}>Owners {vehicle.previousOwners ?? "Unknown"} · Accident history {vehicle.accidentHistoryKnown ? vehicle.accidentHistory ? "Reported" : "Clear" : "Unknown until inspection"}</Text>{owned && <Text style={s.copy}>Days in stock {vehicle.daysInStock} · Repair €{vehicle.repairCost.toLocaleString()} · Preparation €{vehicle.preparationCost.toLocaleString()} · Holding €{vehicle.holdingCost.toLocaleString()}</Text>}</Card>
    {marketVehicle && dealership && <><SectionTitle>Acquire vehicle</SectionTitle><PrimaryButton title={`BUY · €${vehicle.sellerPrice.toLocaleString()}`} disabled={game.cash < vehicle.sellerPrice} onPress={() => run("Buy vehicle", `Seller price €${vehicle.sellerPrice.toLocaleString()}\nPotential margin €${(vehicle.estimatedMarketValue - vehicle.sellerPrice).toLocaleString()}\nTime: 2 hours`, (state) => buyVehicle(state, dealership.id, vehicle.id), true)} /><PrimaryButton title={vehicle.inspected ? `INSPECTED · ${vehicle.inspectionAccuracy}% ACCURACY` : "INSPECT · €280 · 3 HOURS"} tone="dark" disabled={vehicle.inspected} onPress={() => run("Inspect vehicle", "Cost €280 · Time 3 hours\nMay reveal hidden repair need and accident history.", (state) => inspectVehicle(state, vehicle.id))} /><Card style={s.card}><Label>Seller asks €{vehicle.sellerPrice.toLocaleString()}</Label><TextInput accessibilityLabel="Negotiation offer" placeholder="Your counteroffer" placeholderTextColor={colors.muted} keyboardType="numeric" value={offer} onChangeText={setOffer} style={s.input} /><PrimaryButton title="NEGOTIATE · 1 HOUR" tone="dark" onPress={() => { try { const result = negotiateVehicle(game, vehicle.id, Number(offer)); update(() => result.state); Alert.alert(`Seller: ${result.outcome}`, result.counterOffer ? `Counteroffer €${result.counterOffer.toLocaleString()}` : result.outcome === "ACCEPT" ? "Your price was accepted." : "The offer was rejected."); } catch (error) { Alert.alert("Negotiation failed", (error as Error).message); } }} /></Card></>}
    {owned && dealership && <><SectionTitle>Workshop</SectionTitle>{vehicle.workOrder ? <Card><Label>Work in progress</Label><Text style={s.copy}>{vehicle.workOrder.level} · completion is processed through game time.</Text></Card> : <>{(Object.keys(REPAIRS) as RepairLevel[]).map((level) => <PrimaryButton key={level} title={`${level} REPAIR · FROM €${REPAIRS[level].baseCost.toLocaleString()} · ${REPAIRS[level].days} DAYS`} tone="dark" disabled={vehicle.status === "SOLD"} onPress={() => run(`${level} repair`, "Final cost and duration depend on repair need and mechanic skill.", (state) => repairVehicle(state, dealership.id, vehicle.id, level))} />)}<SectionTitle>Cosmetic preparation</SectionTitle>{(Object.keys(PREPARATIONS) as PreparationLevel[]).map((level) => <PrimaryButton key={level} title={`${level.replaceAll("_", " ")} · €${PREPARATIONS[level].cost.toLocaleString()} · ${PREPARATIONS[level].days} DAYS`} tone="dark" disabled={vehicle.status === "SOLD"} onPress={() => run(level, "Cost and duration improve with a skilled detailer.", (state) => prepareVehicle(state, dealership.id, vehicle.id, level))} />)}</>}
    <SectionTitle>Pricing & sale</SectionTitle><Card style={s.card}><Text style={s.copy}>Recommended €{range.low.toLocaleString()}–€{range.high.toLocaleString()}</Text>{(["FAST_SALE", "MARKET_PRICE", "MAX_PROFIT"] as PriceStrategy[]).map((strategy) => <PrimaryButton key={strategy} title={strategy.replaceAll("_", " ")} tone="dark" disabled={vehicle.status === "IN_REPAIR" || vehicle.status === "SOLD"} onPress={() => update((state) => listVehicle(state, dealership.id, vehicle.id, strategy))} />)}<TextInput accessibilityLabel="Custom asking price" placeholder="Custom asking price" placeholderTextColor={colors.muted} keyboardType="numeric" value={custom} onChangeText={setCustom} style={s.input} /><PrimaryButton title="LIST AT CUSTOM PRICE" disabled={!Number(custom) || vehicle.status === "IN_REPAIR" || vehicle.status === "SOLD"} onPress={() => update((state) => listVehicle(state, dealership.id, vehicle.id, "CUSTOM", Number(custom)))} /></Card>{vehicle.status === "LISTED" && <><PrimaryButton title={`ACCEPT WALK-IN BUYER · €${(vehicle.askingPrice ?? 0).toLocaleString()}`} onPress={() => run("Complete vehicle sale", "This immediately accepts a buyer at the current asking price.", (state) => sellVehicle(state, dealership.id, vehicle.id), true)} /><PrimaryButton title="REMOVE LISTING" tone="dark" onPress={() => update((state) => removeVehicleListing(state, dealership.id, vehicle.id))} /></>}
    <SectionTitle>Vehicle history</SectionTitle>{vehicle.history.slice(0, 8).map((entry) => <Card key={entry.id} style={s.card}><Label>{entry.type}</Label><Text style={s.copy}>{entry.description}</Text></Card>)}</>}
  </ScrollView>;
}
const s = StyleSheet.create({ root: { flex: 1, backgroundColor: colors.bg, padding: 18 }, content: { paddingTop: 38, paddingBottom: 110, gap: 12 }, kicker: { color: colors.gold, fontWeight: "900", letterSpacing: 1 }, title: { color: colors.text, fontSize: 31, fontWeight: "900" }, variant: { color: colors.gold, fontWeight: "700", fontSize: 16 }, hero: { flexDirection: "row", flexWrap: "wrap", gap: 20 }, card: { gap: 10 }, copy: { color: colors.muted, lineHeight: 21 }, input: { minHeight: 50, borderRadius: 14, backgroundColor: colors.surface2, borderColor: colors.border, borderWidth: 1, color: colors.text, paddingHorizontal: 14, fontSize: 16 } });
