import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { Card, PrimaryButton, SectionTitle } from '@/components/ui';
import { respondToFamilyEvent } from '@/game/relationships/family';
import { daysBetween, relationLabel } from '@/game/time/time';
import { useGameStore } from '@/store/gameStore';
import { colors, spacing } from '@/theme';

const relationName = { MOTHER: 'Mother', FATHER: 'Father', BROTHER: 'Brother', GRANDMOTHER: 'Grandmother', GRANDFATHER: 'Grandfather' } as const;
export default function Family() {
  const game=useGameStore(state=>state.game)!; const update=useGameStore(state=>state.update); const openEvents=game.familyEvents.filter(event=>event.status==='OPEN');
  const decide=(id:string,decision:'ACCEPTED'|'DECLINED'|'IGNORED')=>{try{update(state=>respondToFamilyEvent(state,id,decision))}catch(error){Alert.alert('Event unavailable',(error as Error).message)}};
  return <ScrollView style={s.root} contentContainerStyle={s.content}><Text onPress={()=>router.back()} style={s.back}>‹ Back</Text><Text style={s.kicker}>LIFE · FAMILY</Text><Text style={s.title}>Your people</Text><Text style={s.subtitle}>Time and attention build relationships. Money alone cannot.</Text>
    {openEvents.length>0&&<><SectionTitle>Family moments</SectionTitle>{openEvents.map(event=><Card key={event.id} style={s.event}><Text style={s.eventTitle}>{event.title}</Text><Text style={s.eventCopy}>{event.description}</Text><View style={s.actionRow}><View style={s.flex}><PrimaryButton title="ACCEPT" onPress={()=>event.type==='BIRTHDAY'?router.push(`/family/${event.memberId}` as never):decide(event.id,'ACCEPTED')}/></View><View style={s.flex}><PrimaryButton title="DECLINE" tone="dark" onPress={()=>decide(event.id,'DECLINED')}/></View></View></Card>)}</>}
    <SectionTitle>Family</SectionTitle>{game.relationships.map(member=>{const days=member.lastInteractionGameDate?daysBetween(member.lastInteractionGameDate,game.date):null;return <Pressable key={member.id} onPress={()=>router.push(`/family/${member.id}` as never)}><Card style={s.person}><View style={s.avatar}><Text style={s.initial}>{member.name.slice(0,1)}</Text></View><View style={s.details}><View style={s.between}><View><Text style={s.name}>{member.name}</Text><Text style={s.relation}>{relationName[member.relationType]}</Text></View><Text style={[s.status,member.contactStatus!=='active'&&s.statusWarn]}>{member.contactStatus.replace('_',' ')}</Text></View><View style={s.metrics}><Text style={s.metric}>Relationship · {relationLabel(member.relationshipScore)}</Text><Text style={s.metric}>Mood · {member.mood}</Text><Text style={s.last}>{days===null?'No recent interaction':days===0?'Contacted today':`Last interaction · ${days} days ago`}</Text></View><Text style={s.open}>OPEN PROFILE →</Text></View></Card></Pressable>})}
  </ScrollView>;
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:colors.bg},content:{padding:spacing.md,paddingTop:55,paddingBottom:90},back:{color:colors.gold,fontWeight:'800',fontSize:17},kicker:{color:colors.gold,fontSize:10,fontWeight:'900',letterSpacing:1.5,marginTop:22},title:{color:colors.text,fontSize:34,fontWeight:'900',marginTop:5},subtitle:{color:colors.muted,lineHeight:20,marginTop:7,marginBottom:2},person:{flexDirection:'row',marginBottom:11,padding:17},avatar:{width:58,height:58,borderRadius:20,backgroundColor:'#29251D',borderWidth:1,borderColor:'#5A492A',alignItems:'center',justifyContent:'center',marginRight:14},initial:{fontSize:24,fontWeight:'900',color:colors.gold},details:{flex:1},between:{flexDirection:'row',justifyContent:'space-between'},name:{color:colors.text,fontSize:19,fontWeight:'900'},relation:{color:colors.muted,marginTop:2},status:{color:colors.green,fontSize:10,fontWeight:'900',textTransform:'uppercase'},statusWarn:{color:colors.gold},metrics:{marginTop:12,gap:3},metric:{color:colors.text,fontSize:12},last:{color:colors.muted,fontSize:11},open:{color:colors.gold,fontSize:11,fontWeight:'900',letterSpacing:.7,marginTop:13},event:{gap:10,marginBottom:10,borderColor:'#5A492A'},eventTitle:{color:colors.text,fontWeight:'900',fontSize:17},eventCopy:{color:colors.muted,lineHeight:19},actionRow:{flexDirection:'row',gap:8},flex:{flex:1}});
