import { Alert, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useState } from 'react';
import { Card, Label, Money, PrimaryButton, SectionTitle } from '@/components/ui';
import { MARKET_OFFERS } from '@/config/balance';
import { buyItem, listItem } from '@/game/businesses/reselling';
import { businessValue } from '@/game/economy/economy';
import { useGameStore } from '@/store/gameStore';
import { colors, spacing } from '@/theme';

function InventoryRow({ item }: { item: ReturnType<typeof useGameStore.getState>['game'] extends infer G ? any : never }) {
  const update = useGameStore(s => s.update); const [price, setPrice] = useState(String(item.marketValue));
  return <Card style={s.card}><View style={s.between}><View><Text style={s.item}>{item.name}</Text><Text style={s.meta}>Paid €{item.purchasePrice} · Value €{item.marketValue}</Text></View><Text style={s.demand}>{item.demand}</Text></View>{item.listedPrice ? <Text style={s.listed}>Listed for €{item.listedPrice}</Text> : <View style={s.listRow}><TextInput value={price} onChangeText={setPrice} keyboardType="numeric" style={s.input}/><View style={{flex:1}}><PrimaryButton title="LIST" onPress={()=>{const value=Number(price);try{update(g=>listItem(g,item.id,value))}catch(e){Alert.alert('Invalid price',(e as Error).message)}}}/></View></View>}</Card>
}
export default function Business(){const game=useGameStore(s=>s.game)!;const update=useGameStore(s=>s.update);const b=game.businesses[0];return <ScrollView style={s.root} contentContainerStyle={s.content}><Text style={s.kicker}>MY BUSINESSES</Text><Text style={s.title}>Reselling</Text><Card style={s.summary}><View><Label>Business value</Label><Money value={businessValue(game)}/></View><View><Label>Profit</Label><Money value={b.revenue-b.expenses}/></View><View><Label>Inventory</Label><Text style={s.metric}>{b.inventory.length}</Text></View><View><Label>Items sold</Label><Text style={s.metric}>{b.sales.length}</Text></View></Card><SectionTitle>Market</SectionTitle>{MARKET_OFFERS.map(o=><Card key={o.id} style={s.card}><View style={s.between}><View style={{flex:1}}><Text style={s.item}>{o.name}</Text><Text style={s.meta}>{o.condition} · {o.demand} demand</Text></View><View><Money value={o.purchasePrice}/><Text style={s.value}>Value €{o.marketValue}</Text></View></View><PrimaryButton title="BUY" disabled={game.cash<o.purchasePrice} onPress={()=>{try{update(g=>buyItem(g,o))}catch(e){Alert.alert('Purchase failed',(e as Error).message)}}}/></Card>)}<SectionTitle>Inventory</SectionTitle>{b.inventory.length===0?<Card><Text style={s.empty}>Buy your first product, choose a price, then advance time to find a buyer.</Text></Card>:b.inventory.map(i=><InventoryRow key={i.id} item={i}/>) }<SectionTitle>Sales history</SectionTitle>{b.sales.length===0?<Text style={s.empty}>No sales yet.</Text>:b.sales.map(x=><View key={x.id} style={s.sale}><Text style={s.item}>{x.itemName}</Text><Text style={{color:x.profit>=0?colors.green:colors.red,fontWeight:'900'}}>+€{x.profit}</Text></View>)}</ScrollView>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:colors.bg},content:{padding:spacing.md,paddingTop:60,paddingBottom:120},kicker:{color:colors.gold,fontSize:10,fontWeight:'900',letterSpacing:1.5},title:{color:colors.text,fontSize:34,fontWeight:'900',marginTop:6,marginBottom:18},summary:{flexDirection:'row',flexWrap:'wrap',gap:22},metric:{color:colors.text,fontSize:22,fontWeight:'900',marginTop:4},card:{gap:14,marginBottom:10},between:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},item:{color:colors.text,fontSize:16,fontWeight:'800'},meta:{color:colors.muted,fontSize:12,marginTop:5},demand:{color:colors.green,fontWeight:'800'},value:{color:colors.muted,fontSize:10,textAlign:'right'},listed:{color:colors.green,fontWeight:'800'},listRow:{flexDirection:'row',gap:10},input:{width:100,height:48,borderRadius:14,backgroundColor:colors.surface2,color:colors.text,paddingHorizontal:14,borderWidth:1,borderColor:colors.border,fontSize:16},empty:{color:colors.muted,lineHeight:21},sale:{flexDirection:'row',justifyContent:'space-between',paddingVertical:14,borderBottomWidth:1,borderBottomColor:colors.border}});
