import { Alert, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { Card, Label, Money, PrimaryButton, SectionTitle } from '@/components/ui';
import { useGameStore } from '@/store/gameStore';
import { monthlyExpenses, monthlyIncome, netWorth, totalBankDebt, totalPersonalDebt } from '@/game/economy/economy';
import { ageAt, formatGameDate, formatGameTime } from '@/game/time/time';
import { colors, spacing } from '@/theme';

export default function Home() {
  const game = useGameStore(s => s.game)!; const advance = useGameStore(s => s.advanceDay);
  const income = monthlyIncome(game), expenses = monthlyExpenses(game);
  return <ScrollView style={styles.root} contentContainerStyle={styles.content}>
    <View style={styles.header}><View><Text style={styles.hello}>WELCOME BACK</Text><Text style={styles.name}>{game.player.firstName}</Text></View><View style={styles.date}><Text style={styles.dateText}>{formatGameTime(game)}</Text><Text style={styles.age}>AGE {ageAt(game.player.birthYear, game.date)}</Text></View></View>
    <Card style={styles.hero}><Label>Available cash</Label><Money value={game.cash} large /><View style={styles.heroBottom}><View><Label>Net worth</Label><Money value={netWorth(game)} /></View><View><Label>Cashflow</Label><Text style={[styles.flow, { color: income - expenses >= 0 ? colors.green : colors.red }]}>{income - expenses >= 0 ? '+' : '-'}€{Math.abs(income - expenses).toLocaleString()}</Text></View></View></Card>
    <View style={styles.grid}><Card style={styles.small}><Label>Income</Label><Money value={income} /></Card><Card style={styles.small}><Label>Expenses</Label><Money value={expenses} /></Card><Card style={styles.small}><Label>Bank debt</Label><Money value={totalBankDebt(game)} /></Card><Card style={styles.small}><Label>Family debt</Label><Money value={totalPersonalDebt(game)} /></Card></View>
    <SectionTitle>Quick actions</SectionTitle><View style={styles.actions}><PrimaryButton title="EARN MONEY" onPress={() => router.push('/earn')} /><PrimaryButton title="BANK" tone="dark" onPress={() => router.push('/bank')} /><PrimaryButton title="FAMILY" tone="dark" onPress={() => router.push('/family')} /><PrimaryButton title="+1 DAY" tone="dark" onPress={() => { advance(); Alert.alert('A new day', 'Listings were checked for buyers.'); }} /></View>
    <SectionTitle>Recent activity</SectionTitle>{game.transactions.length === 0 ? <Card><Text style={styles.empty}>Your story is waiting. Complete your first job.</Text></Card> : game.transactions.slice(0, 6).map(tx => <View key={tx.id} style={styles.tx}><View><Text style={styles.txTitle}>{tx.description}</Text><Text style={styles.txDate}>{formatGameDate(tx.gameDate)}</Text></View><Text style={[styles.txAmount, { color: ['JOB_INCOME','LOAN_RECEIVED','FAMILY_LOAN_RECEIVED','BUSINESS_REVENUE'].includes(tx.type) ? colors.green : colors.text }]}>{['JOB_INCOME','LOAN_RECEIVED','FAMILY_LOAN_RECEIVED','BUSINESS_REVENUE'].includes(tx.type) ? '+' : '-'}€{tx.amount.toLocaleString()}</Text></View>)}
  </ScrollView>;
}
const styles = StyleSheet.create({ root: { flex: 1, backgroundColor: colors.bg }, content: { padding: spacing.md, paddingTop: 60, paddingBottom: 120 }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end', marginBottom: 20 }, hello: { color: colors.gold, fontSize: 10, fontWeight: '900', letterSpacing: 1.5 }, name: { color: colors.text, fontSize: 29, fontWeight: '900' }, date: { alignItems: 'flex-end' }, dateText: { color: colors.text, fontWeight: '700' }, age: { color: colors.muted, fontSize: 11, marginTop: 3 }, hero: { backgroundColor: '#171923', padding: 22 }, heroBottom: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 26, paddingTop: 18, borderTopWidth: 1, borderTopColor: colors.border }, flow: { fontSize: 20, fontWeight: '900', marginTop: 4 }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: 10 }, small: { width: '48%' }, actions: { gap: 10 }, empty: { color: colors.muted, lineHeight: 21 }, tx: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 14, borderBottomColor: colors.border, borderBottomWidth: 1 }, txTitle: { color: colors.text, fontWeight: '700' }, txDate: { color: colors.muted, fontSize: 11, marginTop: 4 }, txAmount: { fontWeight: '900', fontSize: 16 } });
