import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { Card, PrimaryButton, SectionTitle } from '@/components/ui';
import { relationLabel } from '@/game/time/time';
import { useGameStore } from '@/store/gameStore';
import { colors, spacing } from '@/theme';

export default function Life(){const game=useGameStore(state=>state.game)!;const average=Math.round(game.relationships.reduce((sum,member)=>sum+member.relationshipScore,0)/game.relationships.length);const events=game.familyEvents.filter(event=>event.status==='OPEN').length;return <ScrollView style={s.root} contentContainerStyle={s.content}><Text style={s.kicker}>YOUR LIFE</Text><Text style={s.title}>Relationships</Text><Text style={s.subtitle}>Success means more when you have people to share it with.</Text><Card style={s.hero}><View style={s.icon}><Ionicons name="heart" size={28} color={colors.gold}/></View><View style={s.heroCopy}><Text style={s.heroTitle}>Family</Text><Text style={s.heroText}>{game.relationships.length} people · {relationLabel(average)} overall</Text><Text style={s.event}>{events?`${events} family moment${events===1?'':'s'} waiting`:'Everyone is doing okay'}</Text></View></Card><PrimaryButton title="OPEN FAMILY" onPress={()=>router.push('/family')}/><SectionTitle>Social pulse</SectionTitle><View style={s.grid}>{game.relationships.map(member=><Card key={member.id} style={s.person}><View style={s.avatar}><Text style={s.initial}>{member.name[0]}</Text></View><Text style={s.personName}>{member.name}</Text><Text style={s.personMeta}>{member.mood} · {member.relationshipScore}/100</Text></Card>)}</View></ScrollView>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:colors.bg},content:{padding:spacing.md,paddingTop:60,paddingBottom:120},kicker:{color:colors.gold,fontSize:10,fontWeight:'900',letterSpacing:1.5},title:{color:colors.text,fontSize:34,fontWeight:'900',marginTop:5},subtitle:{color:colors.muted,lineHeight:20,marginTop:7,marginBottom:20},hero:{flexDirection:'row',alignItems:'center',marginBottom:10,borderColor:'#5A492A'},icon:{width:58,height:58,borderRadius:19,backgroundColor:'#29251D',alignItems:'center',justifyContent:'center',marginRight:14},heroCopy:{flex:1},heroTitle:{color:colors.text,fontSize:21,fontWeight:'900'},heroText:{color:colors.muted,marginTop:4},event:{color:colors.gold,fontSize:12,fontWeight:'800',marginTop:7},grid:{flexDirection:'row',flexWrap:'wrap',gap:9},person:{width:'48%',alignItems:'center'},avatar:{width:45,height:45,borderRadius:15,backgroundColor:colors.surface2,alignItems:'center',justifyContent:'center'},initial:{color:colors.gold,fontSize:18,fontWeight:'900'},personName:{color:colors.text,fontWeight:'900',marginTop:9},personMeta:{color:colors.muted,fontSize:11,marginTop:3}});
